import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClerkProviderClient from "./clerk/ClerkProviderClient";
import AuthStatus from "./clerk/AuthStatus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* This basically wraps our entire page inside the clerk client, so that clerk components can be used freely inside */}
        <ClerkProviderClient>
          <div className="w-full max-w-6xl mx-auto px-6">
            <header className="flex items-center justify-between py-4">
              <div />
              <AuthStatus />
            </header>
          </div>
          {children}
        </ClerkProviderClient>
      </body>
    </html>
  );
}
